" General config stuff
set autoindent softtabstop=2 shiftwidth=2 expandtab
set backspace=indent,eol,start
set number relativenumber
set colorcolumn=81
set showmatch
filetype plugin indent on
syntax on
let mapleader=" "
let maplocalleader="\\"
set hlsearch
set encoding=utf-8

" Indentation settings for different filetypes
autocmd FileType c,cpp,javascript,java,lua,xml setlocal shiftwidth=4 softtabstop=4

" Smart relative line numbering
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

" Perform spell check in tex file
augroup spellcheck
  autocmd!
  autocmd FileType tex inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
augroup END

" Code folding
set foldenable
set foldmethod=syntax
set foldlevel=0

" View settings
set viewoptions=cursor,folds,slash,unix

" Font
set guifont=Menlo\ Regular:h18

" GVim options
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

" Colour compatibility settings
let base16colorspace=256
set t_Co=256
set background=dark
set termguicolors

" Theme
colorscheme base16-tomorrow-night

" Backup directory
set backupdir=~/.vim-backup,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-backup,~/.tmp,~/tmp,/var/tmp,/tmp

" Toggle paste mode on/off with F2.
set pastetoggle=<F2>

" Save and close shortcuts
nnoremap <silent> <leader>w :w<CR>
nnoremap <silent> <leader>q :q<CR>
nnoremap <silent> <leader><S-q> :q!<CR>

" Reload .vimrc
nnoremap <silent> <leader>s :source ~/.vimrc<CR>

" Toggle conceallevel 2/0
nnoremap coe :setlocal conceallevel=<c-r>=&conceallevel == 0 ? '2' : '0'<CR><CR>
nnoremap <silent> <F3> :setlocal spell! spelllang=en_gb<CR>

" Toggle scrolloff
nnoremap <silent> <Leader>zz :let &scrolloff=24-&scrolloff<CR>

" Enter normal mode convenient binding
inoremap jj <ESC>

" Use gc to swap current character with the next without changing cursor
" position.
:nnoremap <silent> gc xph

" Use gw to swap current word with the next without changing cursor position.
:nnoremap <silent> gw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>:nohlsearch<CR>

" Re-select last changed text
noremap gV `[v`]

" Command-T config
nnoremap <silent> <C-t> :Files<CR>

" NerdTree config
let NERDTreeMapActivateNode='l'
let NERDTreeShowHidden=1
nmap <silent> <leader>n :NERDTreeToggle<CR>
nmap <silent> <leader>j :NERDTreeFind<CR>
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']

" GitGutter config - always display gutter
" First checks if gutters are supported in this version of vim
if exists('&signcolumn')  " Vim 7.4.2201
  set signcolumn=yes
else
  let g:gitgutter_sign_column_always = 1
endif

" SimpylFold config
" Show docstrings for folded code
let g:SimpylFold_docstring_preview=1

" Airline config
let g:airline_theme='base16_tomorrow'

" delimitMate config
let delimitMate_expand_cr = 2
let delimitMate_nesting_quotes = ['"', '`', "'"]

" vimtex config
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = 'latex'
let g:vimtex_view_method='zathura'
let g:tex_conceal='abdmg'

" Python config
let g:python_host_prog = expand('$HOME') . '/.virtualenvs/pynvim2/bin/python'
let g:python3_host_prog = expand('$HOME') . '/.virtualenvs/pynvim3/bin/python'

" suda.vim config
let g:suda_smart_edit = 1


" neovim specific configuration {{{
if has('nvim')

  " ALE config {{{

  " View details
  nnoremap <silent> <leader>d :ALEDetail<CR>

  let g:ale_python_auto_pipenv = 1

  " Linter options
  let g:ale_linters = {
    \ 'c': ['cppcheck', 'clangcheck', 'clangtidy', 'cquery'],
    \ 'python': ['flake8', 'pyflakes', 'pylint']
    \ }

  " Fixer options
  let g:ale_fixers = {
    \ 'javascript': ['prettier'],
    \ }

  " }}}

  " coc.nvim config {{{

  let g:coc_disable_startup_warning = 1

  " Use <c-space> to trigger completion
  inoremap <silent><expr> <C-space> coc#refresh()

  " Show signature help
  nnoremap <silent> <C-h> :call CocActionAsync('showSignatureHelp')<CR>

  " Use <Tab> and <S-Tab> to navigate the completion list
  inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<C-v><Tab>"

  " Use <CR> to confirm completion
  imap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u<Plug>delimitMateCR"

  " Close the preview window when completion is done
  autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

  " Navigate snippet placeholders
  "let g:coc_snippet_next = '<C-j>'
  "let g:coc_snippet_prev = '<C-k>'

  " Use `[c` and `]c` to navigate diagnostics
  nmap <silent> [c <Plug>(coc-diagnostic-prev)
  nmap <silent> ]c <Plug>(coc-diagnostic-next)

  " Keys for gotos
  nmap <leader>ld <Plug>(coc-definition)
  nmap <leader>ly <Plug>(coc-type-definition)
  nmap <leader>li <Plug>(coc-implementation)
  nmap <leader>lr <Plug>(coc-references)

  " Format entire file
  nnoremap <silent> <leader>lf :call CocAction('format')<CR>

  " Show commands
  nnoremap <silent> <leader>lm :<C-u>CocList commands<CR>

  " Rename current word
  nmap <leader>rn <Plug>(coc-rename)

  " Format selected region
  nmap <leader>f <Plug>(coc-format-selected)
  xmap <leader>f <Plug>(coc-format-selected)

  " Do codeAction of selected region, ex: `<leader>aap` for current paragraph
  xmap <leader>a <Plug>(coc-codeaction-selected)
  nmap <leader>a <Plug>(coc-codeaction-selected)
  " Do codeAction of current line
  nmap <leader>ac <Plug>(coc-codeaction)
  " Fix autofix problem of current line
  nmap <silent> <leader>laf :CocFix<CR>

  " Use `:OR` for organize import of current buffer
  command! -nargs=0 OR :call CocAction('runCommand',
        \ 'editor.action.organizeImport')

  " Show documentation in preview window
  nnoremap <silent> <leader>lh :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction

  " Extensions to always install
  let g:coc_global_extensions = [
    \ 'coc-vimtex',
    \ 'coc-snippets',
    \ 'coc-marketplace'
    \ ]

  " }}}

endif
" }}}


" Load starsearch.vim
:source ~/.vim/macros/starsearch/plugin/starsearch.vim

" Plugin list
call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'vim-scripts/visualrepeat'
Plug 'tpope/vim-unimpaired'
Plug 'andymass/vim-matchup'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'tmhedberg/simpylfold'
Plug 'Raimondi/delimitMate'
Plug 'wellle/targets.vim'
Plug 'lervag/vimtex'
Plug 'rhysd/vim-grammarous'
Plug 'honza/vim-snippets'
Plug 'lambdalisue/suda.vim'
Plug 'thosakwe/vim-flutter'
Plug 'vim-scripts/restore_view.vim'
if has ('nvim')
  Plug 'w0rp/ale'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'Shougo/neco-vim'
  Plug 'neoclide/coc-neco'
  Plug 'sakhnik/nvim-gdb', { 'do': ':!./install.sh \| UpdateRemotePlugins' }
  Plug 'junegunn/fzf.vim'
endif
" Syntax plugins
Plug 'vim-scripts/django.vim'
Plug 'nikvdp/ejs-syntax'
Plug 'isruslan/vim-es6'
Plug 'glench/vim-jinja2-syntax'
Plug 'sheerun/vim-polyglot'
call plug#end()
