#!/bin/bash

sleep 2

IFS=':' read -r -a MONITORS <<< "$AUTORANDR_MONITORS"

i3-msg "[workspace=\"^(1|3|5)\"] move workspace to output ${MONITORS[0]}"
if [ -n ${MONITORS[1]} ]
then
  i3-msg "[workspace=\"^(2|4|6)\"] move workspace to output ${MONITORS[1]}"
fi
