#!/bin/bash

sleep 2s

# Get monitor configuration
MONITORS=$(xrandr | grep " connected " | awk '{ print$1 }' | paste -d\; -s -)
IFS=';' read -r -a MONITORS <<< "$MONITORS"
PRIMARY_MONITOR=$(xrandr | grep " primary " | awk '{ print$1 }' | tail -1)
echo Primary monitor: $PRIMARY_MONITOR

# Rearrange workspaces
i3-msg "[workspace=\"^(1|3|5|7|9)\"] move workspace to output $PRIMARY_MONITOR"

for i in "${MONITORS[@]}"
do
  if [ "$i" != "$PRIMARY_MONITOR" ]; then
    i3-msg "[workspace=\"^(2|4|6|8|0)\"] move workspace to output $i"
  fi
done

# Reset wallpaper
feh --bg-fill ~/Pictures/wallpaper.png

# Restart polybar
~/.config/polybar/launch.sh
