#!/usr/bin/env bash

confirm_menu() {
  local rofi=$1
  local prompt=$2

  local yes=$3
  local no=$4

  local options="$yes\n$no"

  local chosen="$(echo -e "$options" | $rofi -p "$prompt" -dmenu)"

  case $chosen in
    $yes)
      return 0
      ;;
    $no)
      return 1
      ;;
  esac

  return 1
}
