#!/usr/bin/env bash

reboot_menu() {
  local rofi=$1
  local uptime=$(uptime -p | sed -e 's/up //g')

  #reboot="  "
  local reboot="  "
  local windows="  "
  local uefi="  "
  #uefi="  "
  #uefi="  "
  #uefi="  "
  #uefi="  "

  local options="$reboot\n$windows\n$uefi"

  local chosen="$(echo -e "$options" | $rofi -p "UP - $uptime" -dmenu)"

  case $chosen in
    $reboot)
      systemctl reboot
      ;;
    $windows)
      systemctl reboot --boot-loader-entry=auto-windows
      ;;
    $uefi)
      systemctl reboot --boot-loader-entry=auto-reboot-to-firmware-setup
      ;;
  esac
}
