# Add locally installed programs to execution path
if [[ $PATH != *"/.local/bin"* ]]; then
  export PATH=${HOME}/.local/bin:$PATH
fi
if [[ $PATH != *"${HOME}/bin"* ]]; then
  export PATH=${HOME}/bin:$PATH
fi

# Set locale
export LANG=en_GB.UTF-8
