# Add user programs to execution path
if [[ $PATH != *"$HOME/bin"* ]]; then
  export PATH="$PATH:$HOME/.local/bin"
  export PATH="$PATH:$HOME/.cargo/bin"
  export PATH="$PATH:$HOME/.npm/bin"
  export PATH="$PATH:$HOME/bin"
fi

# Set path for NPM global package installations
export NODE_PATH="$HOME/.npm/lib/node_modules"

# Set locale
export LANG=en_GB.UTF-8

export EDITOR=nvim
